// String baseUrl = "https://budgetrip.in/api/"; /// live base url
String baseUrl = "https://anniecabs.com/BudgeTrip/api/";
String userid="";
String useridOTP="";
String loginType="";
String MobileNo="";
String otpStatus="";
String userType="";
String usertoken="";
String MobileNumber="";
String Password="";